type User @table {
  displayName: String!
  email: String
  createdAt: Timestamp!
}

type Hospital @table {
  name: String!
  address: String!
  phoneNumber: String
}

type ShiftType @table {
  name: String!
  description: String
}

type ShiftGroup @table {
  user: User!
  date: Date!
  totalDurationInMinutes: Int!
}

type Shift @table {
  user: User!
  hospital: Hospital!
  shiftType: ShiftType!
  shiftGroup: ShiftGroup
  date: Date!
  startTime: Timestamp!
  endTime: Timestamp!
  durationInMinutes: Int!
  notes: String
}